### PR TITLE
Resolve #12 temporarily

### LINKED ISSUE #12: Please add a feature that allows program to run in a new window
The executable file only runs in VSCode terminal, and this always makes me headache when I needed to input a lot of data.

### PR DESCRIPTION
**Pull request by Anti-Li**

### CODE REVIEW

**Comment by danielpinto8zz6** [comment]
it only works for windows?

**Comment by Anti-Li** [comment]
I think this all this project only works on Windows now, actually.

**Comment by danielpinto8zz6** [comment]
Sorry, I've been busy, I'll merge that soon as possible.
Thanks

**Comment by danielpinto8zz6** [comment]
so, I came up with an idea, vscode has the following settings :
` // Customizes which terminal to run on Linux.
  "terminal.external.linuxExec": "xterm",

  // Customizes which terminal application to run on macOS.
  "terminal.external.osxExec": "Terminal.app",

  // Customizes which terminal to run on Windows.
  "terminal.external.windowsExec": "C:\\Windows\\System32\\cmd.exe",`

so, we can use that setting to get the terminal and that way we can support all platforms

**Comment by Anti-Li** [comment]
I also thought of this idea. But **Linux** itself doesn't have a "start" command, and how to implement the "start" command is terminal emulators' **own** business. We can't always know which option can create a new instance. For example, _zsh_ requires -t, _gnome-terminal_ requires -x, and even some strange terminals don't have this feature at all. It depends on **itself**.

**Comment by Anti-Li** [comment]
But if I use xterm and I haven't gnome-terminal?

**Comment by danielpinto8zz6** [comment]
It works too

**Comment by Anti-Li** [comment]
But it isn't "-e", it's another option.

**Comment by danielpinto8zz6** [comment]
I tested myself... Im linux user

**Comment by Anti-Li** [comment]
Cover my face. 😅 Very Embarrassing.

**Comment by danielpinto8zz6** [comment]
So, for mac I dont know, because I cant test xd

**Comment by Anti-Li** [comment]
Ok……

**Comment by Anti-Li** [comment]
So it is ``${terminalConfiguration.get<string>("linuxExec")} -e 'sh -c "${command}; read -n1 -p "Press any key to continue...""'``

**Comment by Anti-Li** [comment]
In fact, I already made what you say yesterday, but it's not consummate, which has not been completely successful on my classmate's ubuntu virtual machine.

> so, I came up with an idea, vscode has the following settings :
> 
> > // Customizes which terminal to run on Linux.
> > "terminal.external.linuxExec": "xterm",
> > // Customizes which terminal application to run on macOS.
> > "terminal.external.osxExec": "Terminal.app",
> > // Customizes which terminal to run on Windows.
> > "terminal.external.windowsExec": "C:\Windows\System32\cmd.exe"
> 
> so, we can use that setting to get the terminal and that way we can support all platforms

**Comment by danielpinto8zz6** [comment]
So, we have to rework that, 
like, we don't need to use the vscode terminal, if we're launching os specific console we shouldn't call vscode terminal, we can do it by spawn command...
for mac I saw that we can make it work with osascript, I have no way to test it

**Comment by Anti-Li** [comment]
I will implement it in the dev branch, in the foreseeable future...

**Comment by danielpinto8zz6** [comment]
Yes agree

**Comment by danielpinto8zz6** [comment]
https://github.com/danielpinto8zz6/c-cpp-compile-run/commit/f178b9da2d351fc494a95ea8169e3db53b489589 needs to be tested in windows & mac.
actually on linux it only supports gnome terminal and xterm

**Comment by danielpinto8zz6** [comment]
https://github.com/danielpinto8zz6/c-cpp-compile-run/commit/7be5d73e93334c6b71422c0c410621e841193138

**Comment by danielpinto8zz6** [comment]
Confirmed working on linux & windows, still need to be tested on mac

**Comment by Anti-Li** [comment]
But you never know what kind of terminal the user is using. In case it is a new terminal, it is still valid for mine.

**Comment by LazyRen** [comment]
Hi, I'm currently using this plugin in mac environment. Sadly current version does not works for external Terminal app. I created pull request to fix it. Hope it helps!

**Pull request merged**
